apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-helloworld-nginx
  namespace: {{ .Release.Namespace }}
data:
  index.html: |-
    <html>
    <head><title>Octopus Helm Deployment</title></head>
    <body>
    <h1>Octopus Deployment Id: {{ .Values.deploymentId }}</h1>
    <p>Namespace: {{ .Release.Namespace }}</p>
    </body>
    </html>
